# Generated by Django 3.0.9 on 2020-08-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
    ]
