# Generated by Django 3.0.9 on 2020-08-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_auto_20200813_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-title']},
        ),
    ]
