# Generated by Django 3.0.9 on 2020-08-21 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0005_auto_20200819_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='address',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Адрес ресторана'),
        ),
        migrations.AlterField(
            model_name='list',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='list',
            name='mailbox',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
